var gapi = {
    "auth2": {
        // "GoogleUser": {                     "getBasicProfile": function(){return {"getId": function(){},
        //                                                      "getName": function(){},
        //                                                      "getImageUrl": function(){},
        //                                                      "getEmail": function(){}
        //                                                      }}},
        // "init": function(){},
        "getAuthInstance": function(){
            return {"isSignedIn": {"get": function(){},
                                   "listen": function(){} },
                    "signOut": function(){},
                    "signIn": function(){} }}},
    "load": function (){},
    "client": {
        "init": function(){return {"then": function(){}}},
        "sheets": {"spreadsheets": {"values": {"get": 
            function(){return {"then": function(){}}} }}}}
}

// Auto-generated by lein externs
var TopLevel = {
    // "auth2" : function () {},
    // "client" : function () {},
    // "document" : function () {},
    // "gapi" : function () {},
    // "get" : function () {},
    // "getAuthInstance" : function () {},
    // "getElementById" : function () {},
    // "init" : function () {},
    // "isSignedIn" : function () {},
    // "listen" : function () {},
    // "load" : function () {},
    // "sheets" : function () {},
    // "signIn" : function () {},
    // "signOut" : function () {},
    // "spreadsheets" : function () {},
    // "then" : function () {},
    // These two items are keys on a result provided in a then / callback style...    
    "result" : {"values" : []} // missed?
}
